### ISSUE TITLE
3D model

### ISSUE THREAD

**Issue by ghost** [anthonykirby/kicad_microbit_connector#1]
Hi @anthonykirby 

Is this the vertical connector? I can have a go at building the 3D model if that helps.

Thanks

4UCON type 17809
![image](https://cloud.githubusercontent.com/assets/7076027/25002596/2f745a7e-2043-11e7-80f6-30b684ef61db.png)

**Comment by anthonykirby** [comment]
Amazing! Yes, that's right, a 3D model would be great.

Also, thank you for finding the part number - I had only managed to find hobby suppliers so far, so the part number will help with getting larger quantities.

Anthony

**Comment by ghost** [comment]
Happy to help :smile:  

When I searched for the part recently, it took a while until I found a datasheet that had the 4UCON drawing number on it.  I'm not sure if an equivalent part is made by other manufacturers (e.g. TE, Molex, etc).

**Comment by ghost** [comment]
I've got to finish the ends and add some internal detail , but the model is coming along.  And fits your footprint :smile:

![image](https://cloud.githubusercontent.com/assets/7076027/25039868/f5c3f2ce-20fd-11e7-880d-91b6b76e6da8.png)
![image](https://cloud.githubusercontent.com/assets/7076027/25039889/107bd1ea-20fe-11e7-87fa-1ed1a39b1be2.png)

**Comment by ghost** [comment]
PR submitted with completed model: https://github.com/anthonykirby/kicad_microbit_connector/pull/3

![image](https://cloud.githubusercontent.com/assets/7076027/25064912/355f1698-21fd-11e7-8e76-372aa84ec17d.png)
