### ISSUE TITLE
Orientation of footprint vs symbol

### ISSUE THREAD

**Issue by ghost** [anthonykirby/kicad_microbit_connector#4]
Hi @anthonykirby 

The 90 degree version of the connector (4UCON 10156) has pin 1 on the right hand side when viewed from the top of the board and with the socket pointing "up" the board.

![image](https://cloud.githubusercontent.com/assets/7076027/25096008/2a3f8c94-2396-11e7-9f4e-9f56f3008fa3.png)

I guess usually people would plug in the micro:bit so that the LEDs and buttons are facing up in this configuration.  So, pin 1 of the socket maps to pin 22 (GND) of the micro:bit.

![image](https://cloud.githubusercontent.com/assets/7076027/25096053/763980fa-2396-11e7-9658-69b6a3aa9dbf.png)

With the vertical version of the socket, it obviously could be used either way round.  But for consistency, I would expect pin 1 of the socket to map to pin 22 (GND).

In your symbol, it is the other way round, with pin 22 (GND) on pin 80 of the connector.

![image](https://cloud.githubusercontent.com/assets/7076027/25096103/b8d91650-2396-11e7-88a1-fb7b3b007e4d.png)

What do you think about swapping the symbol pins round?

Thanks

**Comment by anthonykirby** [comment]
Interesting question:  I did think about which way to number the pins, and I chose the even-numbered pins because it's easier to convert n<->2n than n<->2n+1 (it's intuitive e.g. that 34 is double 17).  
But that was just thinking about the vertical version: For the right-angle, I agree with you (& then of course vertical & right-angle should be the same).

**Comment by ghost** [comment]
I have done a PR with the pins swapped and a couple of other changes to pass the KLC checks.  See what you think.

And thanks for merging the 3D model.

**Comment by anthonykirby** [comment]
many thanks!
