### ISSUE TITLE
90-degree version compatibility

### ISSUE THREAD

**Issue by SukkoPera** [anthonykirby/kicad_microbit_connector#6]
Sorry for opening an issue for this, but I found no other way to get in touch with you.

I was just wondering if this component is compatible with the 90-degree version, or if the footprint for this is available somewhere else.

Otherwise I can try to contribute it.

**Comment by anthonykirby** [comment]
Hi Giorgioggì,
that's OK, no worries!
Sorry, I don't know if there's a freely available 90-degree version of the library/footprint.
However, the actual 90-degree connectors for are much more commonly available that the straight one (which was hard to find), so it would be worth looking.  If you do find one, please let me know & I can mention it in the README.
thanks
Anthony

**Comment by SukkoPera** [comment]
Hi again Anthony,

just a short follow-up on this discussion: I finally decided to make my own footprint for the 90-degree version of this connector sold by [CoolComponents](https://coolcomponents.co.uk/products/edge-connector-for-bbc-micro-bit), then I had some board made. I received them a few days ago and can now say that it matches the connector perfectly.

My footprint was actually derived from yours, I seem to recall I only needed to alter the vertical spacing between each hole row. In case you are interested in it, you can find it [here](https://github.com/SukkoPera/OpenAmiga600RamExpansion/blob/master/OpenAmiga600RamExpansion.pretty/4UCON_10156_90deg.kicad_mod). It might need some minor rework as I'm not sure I'm not sure I set the "margins" correctly. All I can say is that the holes and silkscreen are correct. Thanks for your work, I mentioned you among the thanks for my project.

PS: Yes, I used this connector on a project totally unrelated with the micro::bit ;).

**Comment by mignon-p** [comment]
Thanks, @SukkoPera!  It looks like your right-angle footprint will also work with the right-angle connector [sold by Adafruit](https://www.adafruit.com/product/3342), because it also has 1.9mm spacing between rows.

(I haven't been able to find the straight version of the connector anywhere.)

**Comment by mignon-p** [comment]
I'm a little puzzled by the orientation of the connector.  Based on the silkscreen, it looks like pin 1 is on the left side of the micro:bit when the micro:bit is inserted face-up.  But in the schematic symbol, pins 1, 3, 5, 7, 9, and 11 are GND, and GND is supposed to be on the right side of the micro:bit.

![microbit_edge_connector](https://user-images.githubusercontent.com/1080008/44891251-22464280-ac93-11e8-8846-a23d1744dfa5.png)

**Comment by SukkoPera** [comment]
Yes, pin numbering might be incorrect for the bbc:micro since, as I mentioned, I used this connector in a project not related to it.

**Comment by mignon-p** [comment]
Here is my version of the right-angle footprint.

[4UCON_10156_90deg.zip](https://github.com/anthonykirby/kicad_microbit_connector/files/2346823/4UCON_10156_90deg.zip)

**Comment by mignon-p** [comment]
I would be interested in contributing my version of the right-angle footprint to the [official KiCad library](https://github.com/KiCad/kicad-footprints).  The official KiCad library is licensed under the [Creative Commons Share-Alike 4.0 license, with an additional exception](https://forum.kicad.info/t/kicad-library-licensing/7856).  Would you two (@anthonykirby and @SukkoPera) be willing to allow your contributions to be distributed under this license?

**Comment by SukkoPera** [comment]
No issue for me. Actually I would be glad if it ended up in there.

**Comment by anthonykirby** [comment]
Yes, of course - I'd be very happy to.
